# .yaml files in this directory are executed workflows:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
# This workflow is triggered on pushes to non-main (or master) branches
# Builds and tests the app (just test)
name: Build and test (self-hosted)

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    # only non-main (and non-master) branches
    branches:
      - "**"
      - "!main"
      - "!master"

env:
  DOCKER_COMPOSE_VERSION: 1.25.4
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1


jobs:
  test_on_push:
    name: Build and test
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Build and test app on the self-hosted runner
        uses: ./.github/actions/self-hosted
        timeout-minutes: 30
        with:
          command: "just test"
